# Generated by Django 4.1.7 on 2024-11-09 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='date_time',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
