# Generated by Django 4.1.7 on 2024-11-09 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_app', '0002_alter_userdetails_date_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetails',
            name='profile_pic',
            field=models.ImageField(upload_to='profile_pics/'),
        ),
    ]
